### ISSUE TITLE
element.matches not working in ie 11. 

### ISSUE THREAD

**Issue by pebble2050** [focus-trap/tabbable#156]
element.matches not working in ie 11. (src/index.js)

**Comment by idoros** [comment]
I assume this fails at [line #24](https://github.com/focus-trap/tabbable/blob/a49f8f0cd6a872497fc52abc06c9458021075058/src/index.js#L124)?

**Comment by stefcameron** [comment]
@pebble2050 Thank you for reporting this! I'll publish an update shortly with the fix from @idoros

**Comment by stefcameron** [comment]
@all-contributors add @pebble2050 for bug

**Comment by stefcameron** [comment]
Fixed in tabbable 5.1.4
