### ISSUE TITLE
Use @testing-library/dom and Jest for tests

### ISSUE THREAD

**Issue by thawkin3** [focus-trap/tabbable#225]
@stefcameron Still interested in re-writing the test suite with DOM Testing Library and Jest? (https://testing-library.com/docs/dom-testing-library/intro/)

I was going to jump on this soon if you still think it'd be a good idea. Let me know!

**Comment by stefcameron** [comment]
Hey, yes, for sure! Please go ahead if you have the time. 😀

**Comment by thawkin3** [comment]
Sweet! Working on it now. 😄

**Comment by stefcameron** [comment]
🎉 Thank you!
