### ISSUE TITLE
Add code coverage badge to the README

### ISSUE THREAD

**Issue by thawkin3** [focus-trap/tabbable#260]
Now that the test suite is converted over to use Jest and DOM Testing Library, what do you think about adding a code coverage badge to the README to show off the code coverage?

I see in the `focus-trap-react` repo we used Codecov along with GitHub Actions for the CI. In this `tabbable` repo it's also using GitHub Actions for the CI, so I assume we can generate the code coverage report there and then feed the results to Codecov, right? Or maybe even generate the badge without using Codecov if that's not something you want to do, and we could just use GitHub Actions directly?

Thoughts?

**Comment by stefcameron** [comment]
@thawkin3 Hey, yes, I see no reason why we couldn't add a Codecov badge to this repo now. We should be able to set it up the same way as in `focus-trap-react`. Both repos are setup the same way with GH actions, etc. Just need to invite the Codecov bot to this repo and connect to it with the `codecov` library.

**Comment by stefcameron** [comment]
Codecov bot now has access to this repo. Just need to start feeding it data. 😄

**Comment by stefcameron** [comment]
You're welcome to do the rest if you want. That will just require a small PR. Otherwise, LMK so we don't double-up.

**Comment by thawkin3** [comment]
Thanks! I'm happy to knock this out. I'll have a PR up hopefully in the next day or two to get this set up.

**Comment by thawkin3** [comment]
Here ya go! https://github.com/focus-trap/tabbable/pull/261
