### ISSUE TITLE
Provide TS typings

### ISSUE THREAD

**Issue by Andarist** [focus-trap/tabbable#40]
While it's possible to type callable signature with static properties in TS it would be better to change exports shape to default export + 2 named exports (which I mention also in https://github.com/davidtheclark/tabbable/issues/39 ).

It would also be better to use mixed exports, even if it means having to use `require('tabbable').default` by CJS consumers - because then TS typings would be accurate. Faking `default` with `module.exports = _default` is a can of worms and might cause issues in webpack.

**Comment by davidtheclark** [comment]
I'm not interested in supporting TypeScript definitions, sorry.

**Comment by Andarist** [comment]
@stefcameron would you be interested in reviving this work?

**Comment by stefcameron** [comment]
@Andarist Seems like it would be a good thing given `focus-trap` and `focus-trap-react` both already have typings. 😄  I'm thinking as a separate `index.d.ts` file, though, not converting `src/index.js` into `src/index.ts` with integrated types -- at least as a first step. I'm in the middle of #58 so I don't really want to mess with things too much upstream. We could easily add typings, though, and do something similar to `focus-trap` with [this](https://github.com/focus-trap/focus-trap/blob/master/package.json#L14) as a light test.
