### ISSUE TITLE
Seeking co-maintainers!

### ISSUE THREAD

**Issue by davidtheclark** [focus-trap/tabbable#42]
I've been shifting my focus away from UI development, so don't plan on addressing new issues myself. If you use this library and want to see development continue, you can make that happen by becoming a co-maintainer — with permissions to triage issues, merge PRs, cut releases, etc.

Please comment below if you're interested!

Another possibility is for a dedicated owner to fork this code and create a new package. I'd be happy to link to that library from the README of this one.

**Comment by postrad** [comment]
Let me know where I can help. I do a lot of Accessibility work for target.com and I am a big fan of this utility!

**Comment by chancestrickland** [comment]
We use this package in Reach UI and I would be more than happy to join the team. Let me know how we can help.

**Comment by chancestrickland** [comment]
Appreciate the quick response here. Let me know if you have any preferences on process or if you're happy to just have me start reviewing PRs and merging updates. I went ahead and forked it just to get dependencies updated and fix the build in Travis, I'll start with that unless you have any objections.

**Comment by davidtheclark** [comment]
@chancestrickland Please feel free to take the reins and act as owner. I'll try to keep an eye on things and will speak up if I disagree with a move — but otherwise go ahead and make & review & merge PRs. When you're ready to publish let me know. After that first publish, I'll give you npm collab access, too.

**Comment by stefcameron** [comment]
@davidtheclark @chancestrickland Given the inter-dependence of this library with `tabbable` and `focus-trap-react`, what do you think about moving this repo to the https://github.com/focus-trap org where we've already moved `focus-trap-react`? I'd still keep this issue open for maintainers, though!

**Comment by stefcameron** [comment]
@davidtheclark Thanks for moving the repo over!

**Comment by stefcameron** [comment]
@davidtheclark Can you confirm whether I have permission to publish this package in NPM? I need to make a release.

**Comment by stefcameron** [comment]
Closing this. Seems like I'm running the show now. 😅
