### ISSUE TITLE
Bug: isDisabledFromFieldset doesn't check the top-most disabled <fieldset>

### ISSUE THREAD

**Issue by DaviDevMod** [focus-trap/tabbable#596]
[isDisabledFromFieldset](https://github.com/focus-trap/tabbable/blob/b341412a8650f3c334f38ebda2200ae4c0d84328/src/index.js#L171) is supposed to tell whether a node is in the first `<legend>` of the top-most disabled `<fieldset>`, but is actually assessing whether a node is in the first `<legend>` of the closest ancestor `<fieldset>`, which is not necessarily the top-most `<fieldset>` containing the node.

**Comment by stefcameron** [comment]
You are right, thank you!

**Comment by stefcameron** [comment]
@all-contributors add @DaviDevMod for bug
