### ISSUE TITLE
Firefox throws an error when checking disabled on non button element

### ISSUE THREAD

**Issue by bakura10** [focus-trap/tabbable#717]
Hi,

I am not sure if this is related to a recent change of Firefox, but today I got this strange error:

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1198915/175234792-c41391d9-ff27-4fc7-9a12-88e7913412b2.png">

After checking this relates to this line: https://github.com/focus-trap/tabbable/blob/master/src/index.js#L405

Apparently, Firefox seems to throw an exception whenever you access the disabled attribute on an element that does not implement it.

Chrome does not experience any issue, but this should probably be changed, by checking the attribute instead.

Thanks :)

**Comment by bakura10** [comment]
Actually, the issue started to appear from focustrap 6.9.2 and may be related to https://github.com/focus-trap/tabbable/issues/666
I downgraded to focustrap 6.9.1 which works, so I am actually unsure if the issue is on Tabbable or FocusTrap :/

**Comment by bakura10** [comment]
Seems to be related to FocusTrap actually. I'm closing this.

**Comment by bakura10** [comment]
Sorry for the numerous messages, I'm re-opening as the issue is actually apparently on Tabbable :(.

**Comment by idoros** [comment]
can you check what element is being checked that throws this error? 

I'm trying to reproduce the error on Firefox `101.0.1` and calling `disabled` on an element without a disable property just returns `undefined`. (see [here](https://jsbin.com/faloyojabu/1/edit?html,js,output)).

**Comment by bakura10** [comment]
My bad, it is on my end. The issue was coming from the fact that I by mistake did this:

<a href="..." is="custom-button">

Where custom-button is a custom element extending HTMLButtonElement. Chrome silently failed but Firefox did not.

Sorry for the false alarm!

**Comment by stefcameron** [comment]
Glad you figured it out! Thanks for closing the issue.
