### ISSUE TITLE
IE support broken in v5.3.2+

### ISSUE THREAD

**Issue by jpveooys** [focus-trap/tabbable#756]
Hi,

https://github.com/focus-trap/tabbable/commit/aa2a699d7e9d37628a7b1208ba700eb85b42a31e#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R284 seems to have broken IE support as IE doesn't implement the `contains` method on `HTMLDocument`. I'm seeing this in IE11 (but according to the README for this project, IE9+ is supported).

From Googling around a workaround might be to fall back to `node.ownerDocument.body.contains()` if `node.ownerDocument.contains()` is undefined.

Thanks

**Comment by stefcameron** [comment]
Thanks for letting me know, and thanks for using tabbable.

Sounds like the same issue as https://github.com/focus-trap/focus-trap-react/issues/746

I'll soon be publishing majors to clearly indicate tabbable, focus-trap, and focus-trap-react no longer support any version of IE as it is officially out of all support.
