### ISSUE TITLE
jsdom issue: 'slot):not([inert]' is not a valid selector

### ISSUE THREAD

**Issue by thumbsupep** [focus-trap/tabbable#982]
If you regenerate package-lock and run tabbable's unit tests, you get the error `SyntaxError: 'slot):not([inert]' is not a valid selector`
I've narrowed this down to the update of one of jsdom's dependencies: `nwsapi@2.2.2` to `nwsapi@2.2.3`
This breaks unit tests for any consumers of tabbable who install latest and use jsdom.

I'm not sure if the fix is re-writing the `[tabindex]:not(slot):not([inert])` selector, or if this is a bug that nwsapi needs to fix. Please advise.

**Comment by sbeugen** [comment]
Can confirm. I have it in a Nuxt3 project, where we use focus-trap, which uses tabbable

**Comment by thumbsupep** [comment]
looks like it relates to https://github.com/dperini/nwsapi/issues/83

**Comment by stefcameron** [comment]
@thumbsupep Thanks for bringing this to my attention. I replied on that issue. I'll see if I can add an override to tabbable's package.json to pin nswapi to v2.2.2 for now until they fix the issue.

**Comment by stefcameron** [comment]
@all-contributors add @thumbsupep for test

**Comment by stefcameron** [comment]
@thumbsupep `tabbable@v6.1.2` should fix the problem for now!

**Comment by stefcameron** [comment]
@thumbsupep @sbeugen There is a proposal over on https://github.com/dperini/nwsapi/issues/83 to modify the Regex that seemed to be the original problem here.

But today, while trying to verify the proposed Regex changes there, I followed these steps again __and could not reproduce the original issue__:

```
$ git clone tabbable
$ rm package-lock.json
# edit package.json to __remove__ the nwsapi override
$ npm install
# this results in nwsapi v2.2.5
$ npm test
```

Originally, `npm test` would fail with the error raised in this issue. But no more. All tests pass. They also all pass with the proposed Regex changes.

Can one of you try your original steps but with the latest version of tabbable (and its dependencies) -- making sure to remove the override from package.json before `npm install`... -- and LMK if it's still an issue for you?
